definitions:
  dto.AddDynamic:
    properties:
      content:
        type: string
      status:
        type: integer
    type: object
  dto.AddPhotoAlbum:
    properties:
      name:
        type: string
      type:
        description: (0 情侣相册；1 个人相册)
        type: string
    type: object
  dto.CouplesInfo:
    properties:
      loverHeaderImg:
        type: string
      loverId:
        type: integer
      loverNickName:
        type: string
      memorialDay:
        description: 纪念日已过去天数
        type: integer
      userHeaderImg:
        type: string
      userId:
        type: integer
      userNickName:
        type: string
    type: object
  dto.DynamicListInfo:
    properties:
      content:
        type: string
      id:
        type: integer
      userId:
        description: 动态发布者id
        type: integer
      userNickName:
        description: 动态发布者的昵称
        type: string
    type: object
  dto.RelationshipBinding:
    properties:
      memorialDate:
        description: 纪念日
        type: integer
      registrationCodeEncrypt:
        description: 加密后的注册码
        type: string
      userId:
        type: integer
    type: object
  dto.RelationshipBinding2:
    properties:
      memorialDate:
        description: 纪念日
        type: integer
      registrationCodeDecryption:
        description: 解密后的注册码
        type: string
      userId:
        type: integer
    type: object
  dto.UpdateDynamic:
    properties:
      content:
        type: string
      id:
        type: integer
      status:
        type: integer
    type: object
  model.ChangePasswordRequest:
    properties:
      newPassword:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.SignRequest:
    properties:
      birthday:
        type: integer
      email:
        type: string
      nickName:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/changePassword:
    post:
      parameters:
      - description: 用户名, 原密码, 新密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"修改成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户密码修改
      tags:
      - User
  /api/v1/couple-detail:
    get:
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 情侣关系展示页面获取成功
          schema:
            $ref: '#/definitions/dto.CouplesInfo'
      security:
      - ApiKeyAuth: []
      summary: 情侣关系展示页面
      tags:
      - Relationship
  /api/v1/couple-detail/:id:
    get:
      parameters:
      - description: ID
        in: query
        name: '"id"'
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 情侣关系展示页面获取成功
          schema:
            $ref: '#/definitions/dto.CouplesInfo'
      security:
      - ApiKeyAuth: []
      summary: 情侣关系展示页面
      tags:
      - Relationship
  /api/v1/dynamic:
    delete:
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"动态删除成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 动态删除
      tags:
      - Dynamic
    get:
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取动态详情成功
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 查看动态详情
      tags:
      - Dynamic
    post:
      parameters:
      - description: 内容、用户id、动态状态
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AddDynamic'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"动态新增成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 动态新增
      tags:
      - Dynamic
    put:
      parameters:
      - description: id,内容,状态,更新时间
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateDynamic'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"动态修改成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 动态修改
      tags:
      - Dynamic
  /api/v1/dynamic/list:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: content
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页大小
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 分页获取动态列表,返回包括列表,总数
          schema:
            $ref: '#/definitions/dto.DynamicListInfo'
      security:
      - ApiKeyAuth: []
      summary: 获取动态列表
      tags:
      - Dynamic
  /api/v1/login:
    post:
      parameters:
      - description: 用户名, 密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 登录请求函数
      tags:
      - User
  /api/v1/photo-album:
    post:
      parameters:
      - description: 相册名称，相册类型
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.AddPhotoAlbum'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"相册创建成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 相册新增
      tags:
      - PhotoAlbum
  /api/v1/relationship:
    delete:
      parameters:
      - description: coupleID
        in: query
        name: coupleId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"情侣关系解绑成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 情侣关系解绑
      tags:
      - Relationship
    post:
      parameters:
      - description: 加密后的注册码，用户id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.RelationshipBinding'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"情侣关系绑定成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 情侣关系绑定（通过链接进行关系绑定）
      tags:
      - Relationship
  /api/v1/relationship2:
    post:
      parameters:
      - description: 未加密注册码，用户id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.RelationshipBinding2'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"情侣关系绑定成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 情侣关系绑定（通过交换注册码进行关系绑定）
      tags:
      - Relationship
  /api/v1/sign:
    post:
      parameters:
      - description: 用户名、密码、邮箱、手机号
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.SignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 注册请求函数
      tags:
      - User
swagger: "2.0"
